[package]
name = "crownpositor-config"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
license = "MIT"
authors = ["marvelxcodes <ramakrishnan0046@gmail.com>"]
repository = "https://github.com/Crown-OS/crownpositor"
homepage = "https://github.com/Crown-OS/crownpositor"
description = "Compositor configuration types for CrownOS."
keywords = ["crownos", "wayland", "compositor", "config"]
categories = ["config", "os::linux-apis"]
readme = "../README.md"
documentation = "https://docs.rs/crownpositor-config"

[dependencies]
crownos-config = { workspace = true }
regex = { workspace = true }
tracing = { workspace = true }
